// components/ScreenshotGallery.tsx
import React from "react";

const screenshots = [
    { src: "Dashboard.jpg", alt: "Dashboard View" },
    { src: "profile1.jpg", alt: "User Profile" },
    { src: "Login.jpg", alt: "Login Page" },
    { src: "form.jpg", alt: "Form Builder" },
    { src: "dark.jpg", alt: "Dark Mode" },
    { src: "mobile.jpg", alt: "Mobile Responsive" },
];

export default function ScreenshotGallery() {
    return (
        <section className="bg-black py-20 px-6 sm:px-10">
            <div className="max-w-7xl mx-auto text-white">
                <h2 className="text-4xl font-bold mb-4">See the Magic in Action</h2>
                <p className="text-lg mb-10 text-gray-400">
                    Explore real interfaces generated by SaaSCloner — from dashboards to billing pages.
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                    {screenshots.map((shot, index) => (
                        <div
                            key={index}
                            className="rounded-2xl overflow-hidden shadow-lg border border-gray-800 hover:scale-105 hover:shadow-2xl transition-all duration-300"
                        >
                            <img
                                src={shot.src}
                                alt={shot.alt}
                                className="w-full h-64 object-cover"
                            />
                            <div className="bg-[#0a0c22] p-4 text-sm text-gray-300">
                                {shot.alt}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}
